#define PIN_WINDDIRECTIONSENSOR A0
#define SYSTEMVOLTAGE			5.0
#define RESOLUTION_ADC			1023.0

#define SD_CS					53

#define SEALEVELPRESSURE_HPA	(1013.25)

#define PIN_ANEMOMETER			3
#define PIN_OMBROMETER			2

#define TIME					5				// in seconds

#define WINDSCALINGFACTOR		2.4

#define RESOLUTION_OMBROMETER	333.76		// ml per m^2
#define OMBROMETERSCALINGFACTOR	1.0